version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    ports:
      - "5001:5000"
    volumes:
      - ./backend:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true

  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    ports:
      - "3001:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
